## for GScores class
setGeneric("name", function(x) standardGeneric("name"))
setGeneric("type", function(x) standardGeneric("type"))
setGeneric("scores", function(object, ranges, ...) standardGeneric("scores"))
setGeneric("gscores", function(x, ranges, ...) standardGeneric("gscores"))
setGeneric("qfun", function(object, ...) standardGeneric("qfun"))
setGeneric("dqfun", function(object, ...) standardGeneric("dqfun"))
setGeneric("gscoresNonSNRs", function(x) standardGeneric("gscoresNonSNRs"))
setGeneric("populations", function(x) standardGeneric("populations"))
setGeneric("defaultPopulation", function(x) standardGeneric("defaultPopulation"))
setGeneric("defaultPopulation<-", function(x, value) standardGeneric("defaultPopulation<-"))
setGeneric("gscoresCategory", function(x) standardGeneric("gscoresCategory"))
setGeneric("gscoresCategory<-", function(x, value) standardGeneric("gscoresCategory<-"))
setGeneric("gscoresTag", function(x) standardGeneric("gscoresTag"))
setGeneric("gscoresTag<-", function(x, value) standardGeneric("gscoresTag<-"))
setGeneric("nsites", function(x) standardGeneric("nsites"))
setGeneric("hdf5Backend", function(x) standardGeneric("hdf5Backend"))
setGeneric("genomeDescription", function(x) standardGeneric("genomeDescription"))
setGeneric("rgscores", function(n, object, ...) standardGeneric("rgscores"))
setGeneric("wgscores", function(x, ranges, ...) standardGeneric("wgscores"))
