## for GScores class
setGeneric("name", function(x) standardGeneric("name"))
setGeneric("type", function(x) standardGeneric("type"))
setGeneric("scores", function(object, ranges, ...) standardGeneric("scores"))
setGeneric("gscores", function(x, ranges, ...) standardGeneric("gscores"))
setGeneric("qfun", function(object, ...) standardGeneric("qfun"))
setGeneric("dqfun", function(object, ...) standardGeneric("dqfun"))
setGeneric("gscoresNonSNRs", function(x) standardGeneric("gscoresNonSNRs"))
setGeneric("populations", function(x) standardGeneric("populations"))
setGeneric("defaultPopulation", function(x) standardGeneric("defaultPopulation"))
setGeneric("defaultPopulation<-", function(x, value) standardGeneric("defaultPopulation<-"))
setGeneric("gscoresGroup", function(x) standardGeneric("gscoresGroup"))
setGeneric("gscoresGroup<-", function(x, value) standardGeneric("gscoresGroup<-"))
setGeneric("gscoresTag", function(x) standardGeneric("gscoresTag"))
setGeneric("gscoresTag<-", function(x, value) standardGeneric("gscoresTag<-"))
setGeneric("nsites", function(x) standardGeneric("nsites"))
setGeneric("genomeDescription", function(x) standardGeneric("genomeDescription"))
